### ISSUE TITLE
OSError: No wkhtmltopdf executable found: "b''"

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [isidroas/code_to_pdf#12]
Hi, thanks a lot for the repo!
I am running into this error when trying to convert the src folder of a c++ program.
cmd: `code_to_pdf --title model_main ./src `

<img width="975" alt="image" src="https://github.com/isidroas/code_to_pdf/assets/22897462/73034bf8-8196-4451-80e4-a00c4ee2afde">

The src folder is structured as below:
<img width="550" alt="image" src="https://github.com/isidroas/code_to_pdf/assets/22897462/bced1e3e-8e1e-4dd3-97bd-e62218dad0dd">

**Comment by Daniel-Trung-Nguyen** [comment]
After installing `wkhtmltopdf`, I ran into this DeprecationError:
<img width="969" alt="image" src="https://github.com/isidroas/code_to_pdf/assets/22897462/e1f8da56-e662-4649-8df8-0da9d5c9980e">

**Comment by Daniel-Trung-Nguyen** [comment]
I believe the version on pypi is not up-to-date. I uninstalled it and reinstalled the lib from github repo and it worked. There was a Debug message as below, but overall this is a very nice implementation. I truely appreciate the effort!
Thanks,
Daniel
<img width="728" alt="image" src="https://github.com/isidroas/code_to_pdf/assets/22897462/775df0f9-9b61-43e1-8b0d-64d995628d98">

**Comment by isidroas** [comment]
Thanks for the report!

I have uploaded the last version to pypi and updated the README to advice of that `wkhtmltopdf` dependency.

Regarding to
```
DEBUG: git.util:Failed checking if running in CYGWIN due to: FileNotFoundError(2,
 'No such file or directory')
```
It seems a trace of the GitPython package.

The only hypothesis I can think is that you don't have git installed

**Comment by Daniel-Trung-Nguyen** [comment]
Thanks, @isidroas ! I worked fine when I installed from github repo. I did have git installed
